steps:
- checkout: self
  submodules: true
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
- script: |
    pip install --upgrade pip
    pip install conan_package_tools
    conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
    conan user
- script: python build.py
